### ISSUE TITLE
looks like not support path with space

### ISSUE THREAD

**Issue by bluelovers** [tunnckoCore/hela3#100]
```
$ "D:\Users\Documents\The Project\nodejs-test\parse-function\node_modules\.bin\hela" build:node
'"D:\Users\Documents\The"' 不是內部或外部命令、可執行的程式或批次檔。
ERR! Error: spawn D:\Users\Documents\The ENOENT
```

**Comment by tunnckoCore** [comment]
I'm seeing that you try to use it frome parse-function. There are npm scripts that uses it, so it should work when called from npm scripts.Because the local `node_modules/.bin` folder is automatically added to your PATH os variable.

**Comment by tunnckoCore** [comment]
I'm working on v3 release in anyway. You can see it at v3-major branch. Or install `@hela/cli`

**Comment by bluelovers** [comment]
@olstenlarck bacause i got error when i wanna try use is by `npm run build`

it also fail when i use `yarn run build` too

---

and nvm, the pr https://github.com/tunnckoCore/parse-function/pull/142

already pass form online auto test

**Comment by tunnckoCore** [comment]
In anyway it's not a poblem in hela. You may encounter such problems in other projects too.

Which `npm` and `yarn` versions you are using?
Try `npm config get user-agent` and `yarn config get user-agent`.

In my projects everyone should use Yarn, otherwise it may have some problems, because both tools behive differently.

At best, you should add `node_modules\.bin` to your `PATH` environment variable. Check out in the internet how this can be fixed and if it works. I'm not using Windows for years. ANd never used Nodejs in Windows.

**Comment by bluelovers** [comment]
npm/6.1.0 node/v10.4.0 win32 x64
yarn/1.7.0 npm/? node/v10.4.0 win32 x64

**Comment by tunnckoCore** [comment]
Huh.

Oh, i think i know why it may be a problem in Windows.

Can you try to add `yarn` here https://github.com/tunnckoCore/parse-function/blob/master/.helarc.json before `hela` and try again. It should work then, because it will use Yarn's resolving mechanism.

**Comment by bluelovers** [comment]
i think problem is ur build script didn't quote path
when u are use exec("bin path") not spawn("bin", ["xxx"])
so u need quote path

https://www.npmjs.com/package/hela-preset-tunnckocore

so it fail when path include space

**Comment by tunnckoCore** [comment]
Actually no, because we use `execa-pro` exactly for this purpose. It supports just definite everything in single string, as in the terminal. Also supports running in series.

**Comment by bluelovers** [comment]
it fail

```
$ "D:\Users\Documents\The Project\nodejs-test\parse-function\node_modules\.bin\hela" clean
[debug:execa] [ '/d',
  '/s',
  '/c',
  '""D:\\Users\\Documents\\The" "Project\\nodejs-test\\parse-function\\node_modules\\hela-preset-tunnckocore\\node_modules\\.bin/rimraf" "D:\\Users\\Documents\\The" "Project\\nodejs-test\\parse-function\\dist""' ]
```

**Comment by tunnckoCore** [comment]
Don't know what are you donig, but try the example from the readme of [execa-pro](https://github.com/tunnckoCore/execa-pro)

```js
const { exec } = require('execa-pro')

async function run () {
  await exec('echo "hello world"', { stdio: 'inherit' })

  // executes in series
  await exec([
    'git add -A',
    'git commit -m "some awesome message"'
  ], { stdio: 'inherit', preferLocal: true })
}

run()
```

**Comment by bluelovers** [comment]
`execa-pro` use `execa`, and i edit `execa/index.js` in `node_modules`



search this
```
spawned = childProcess.spawn(parsed.cmd, parsed.args, parsed.opts);
```
add
```
console.log(parsed.args)
```

look https://www.npmjs.com/package/split-cmd
in readme he also use quote

and execa-pro use this module for split argv

so i think u should add quote for path

**Comment by bluelovers** [comment]
my path is mean file path / folder path

```
'build:node': `${BINDIR}/rollup -c ${FOLDER}/config/node.js`,
```
=>
```
'build:node': `"${BINDIR}/rollup" -c "${FOLDER}/config/node.js"`,
```

-------
```
const clean = `${BINDIR}/rimraf ${cwd('dist')}`
```
=>
```
const clean = `"${BINDIR}/rimraf" "${cwd('dist')}"`
```

**Comment by bluelovers** [comment]
ur execa-pro is 1.0.2

https://github.com/tunnckoCore/execa-pro/blob/2ac61f7af7e069488af67eb3a3cb5655772e7b79/src/index.js#L120-L123

----------

u should use https://www.npmjs.com/package/npm-check-updates

check ur dependencies

**Comment by tunnckoCore** [comment]
Yes, bug was fixed today. Anyway.
