### ISSUE TITLE
example repos

### ISSUE THREAD

**Issue by tomByrer** [tunnckoCore/hela3#106]
Seems like an interesting project.  Have any good example repos using this please?

(Maybe don't bother until after v3 is out....)

**Comment by tunnckoCore** [comment]
Heya. Yea, I've used the v1 or v2 in a couple of repos. Look around the @tunnckoCoreLabs. I'll give links here later if I found some specific ones.

- https://github.com/tunnckoCoreLabs/parse-function
- https://github.com/tunnckoCoreLabs/hela-config-tunnckocore
- https://github.com/tunnckoCoreLabs/get-installed-path
